// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szubssgmgigwloumgcjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6dWJzc2dtZ2lnd2xvdW1nY2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MjM5MDUsImV4cCI6MjA2NTI5OTkwNX0.oIDufRGYQno9UtRDk7WlmLiMTL1oktsDn_xyrXBMAxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);